services:
  redis:
    hostname: redis
    image: redis:8.4
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    
  s3:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    hostname: s3
    ports:
      - 9001:9001
    volumes:
      - s3:/var/images
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: ["minio", "server", "/var/images"]
    healthcheck:
      test: ["CMD", "curl", "--fail-with-body", "http://s3:9000/minio/health/live"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    
  rabbitmq:
    image: rabbitmq:4.2.2
    hostname: rabbitmq
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  sql_db:
    image: postgres:18.1
    hostname: sql
    volumes:
      - sql:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DBNAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SQL_USER}", "-d", "${SQL_DBNAME}"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

    
volumes:
  s3: {}
  sql: {}
  redis: {}
  rabbitmq: {}
