"""Change version column name

Revision ID: 1bb0234a8900
Revises: f6c9c4a53f5b
Create Date: 2025-10-31 15:48:44.553269

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1bb0234a8900'
down_revision: Union[str, Sequence[str], None] = 'f6c9c4a53f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'version', new_column_name='update_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'update_version', new_column_name='version')
    # ### end Alembic commands ###
