"""Remove error code

Revision ID: 5c95c4a62ef1
Revises: 1bb0234a8900
Create Date: 2025-11-20 14:57:21.129490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c95c4a62ef1'
down_revision: Union[str, Sequence[str], None] = '1bb0234a8900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_failed_data', 'error_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_failed_data', sa.Column('error_code', postgresql.ENUM('Unknown', name='errorcode'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
