"""Initial

Revision ID: 7e7572a3f74d
Revises: 
Create Date: 2026-01-25 20:42:24.810485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7572a3f74d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('update_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_status',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('task_completed_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_status.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_failed_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['task_status.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_failed_data')
    op.drop_table('task_completed_data')
    op.drop_table('task_status')
    op.drop_table('task')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
